baseURL = 'https://example.org/'
languageCode = 'en-us'
title = '/home/oliveira-sh'
theme = 'not-much'
copyright = "GPLv3 © {2025}"

[markup]
  [markup.highlight]
    style = 'dracula'
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true


[params]
theme = "dark"
palette = "catpuccin"
showThemeNotice = true
showPostsSummary = true

# Navigation
[menu]
  [[menu.main]]
    identifier = "home"
    name = "home"
    title = "Home"
    url = "/"
    weight = 1
  
  [[menu.main]]
    identifier = "posts"
    name = "posts"
    title = "posts"
    url = "/posts"
    weight = 3
  
  [[menu.main]]
    identifier = "about"
    name = "about"
    title = "About"
    url = "/about"
    weight = 2
  
  [[menu.main]]
    identifier = "github"
    name = "github"
    title = "GitHub"
    url = "https://github.com/imgios/not-much"
    weight = 4

  [[menu.main]]
    identifier = "email"
    name = "email"
    title = "e-mail"
    url = "mailto:0l1ve1r4@proton.me"
    weight = 4