# Simple workflow for deploying static content (from wblog/public) to GitHub Pages
name: Deploy static content to Pages

on:
  # Runs on pushes to the default branch
  push:
    branches: ["main"]

  # Manual trigger
  workflow_dispatch:

permissions:
  contents: read       # read the repo contents
  pages: write         # push to GitHub Pages
  id-token: write      # required for configure-pages

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Pages
        uses: actions/configure-pages@v5

      - name: Upload pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # Only upload the wblog/public directory
          path: wblog/public

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
